"use server";

import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { generateStrategy, buildStrategyName } from "@/lib/ai-strategy";
import type { RiskLevel, TimeframeHorizon } from "@/lib/ai-strategy";
import type { BacktestRunRequest } from "@/types";

// ── Keyword inference ────────────────────────────────────────────────────────

function inferStrategyParams(goal: string): { risk: RiskLevel; timeframe: TimeframeHorizon } {
  const t = goal.toLowerCase();

  let timeframe: TimeframeHorizon = "medium";
  if (/\b(scalp|1m|5m|15m|intraday|day.?trad|hourly|1h)\b/.test(t)) timeframe = "short";
  else if (/\b(weekly|1w|long.?term|invest|months?|yearly|position.?trad)\b/.test(t)) timeframe = "long";

  let risk: RiskLevel = "balanced";
  if (/\b(conservative|safe|low.?risk|protect|capital.?preserv|small.?pos|slow)\b/.test(t)) risk = "conservative";
  else if (/\b(aggressive|bold|high.?risk|max(imum)?|scalp|breakout|volatile|momentum)\b/.test(t)) risk = "aggressive";

  return { risk, timeframe };
}

// ── "Describe" entry point ───────────────────────────────────────────────────
// Accepts plain-English goal + symbol + optional interval override + optional custom name.
// Infers risk/timeframe from keywords so the user never has to pick them.

export async function describeStrategyAction(formData: FormData) {
  const goal           = (formData.get("goal") as string)         || "";
  const symbol         = (formData.get("symbol") as string)       || "SPY";
  const intervalOverride = (formData.get("interval") as string)   || null;
  const customName     = (formData.get("custom_name") as string)  || null;

  const { risk, timeframe } = inferStrategyParams(goal);

  const enriched = new FormData();
  enriched.set("risk", risk);
  enriched.set("timeframe", timeframe);
  enriched.set("symbol", symbol);
  enriched.set("goal", goal);
  if (intervalOverride) enriched.set("interval_override", intervalOverride);
  if (customName)       enriched.set("custom_name", customName);

  return generateAndTestStrategyAction(enriched);
}

// ── Main generation action ───────────────────────────────────────────────────

export async function generateAndTestStrategyAction(formData: FormData) {
  const supabase = createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) throw new Error("Not authenticated");

  const risk           = (formData.get("risk") as RiskLevel)       || "balanced";
  const timeframe      = (formData.get("timeframe") as TimeframeHorizon) || "medium";
  const symbol         = (formData.get("symbol") as string)        || "SPY";
  const goal           = (formData.get("goal") as string)          || "";
  const intervalOverride = (formData.get("interval_override") as string) || null;
  const customName     = (formData.get("custom_name") as string)   || null;

  // ── Generate strategy config ────────────────────────────────────────────
  const generated = generateStrategy(risk, timeframe);
  const effectiveInterval = intervalOverride || generated.interval;

  // Derive analysis interval (one level higher than execution)
  const CONTEXT_TIMEFRAME: Record<string, string> = {
    "1m": "15m", "5m": "30m", "15m": "1h", "30m": "4h",
    "1h": "4h",  "4h": "1d",  "1d": "1w",
  };
  const analysisInterval = CONTEXT_TIMEFRAME[effectiveInterval] ?? null;

  // Build a unique, descriptive name from symbol + goal + template
  const strategyName = buildStrategyName(generated, symbol, goal, customName);
  const runName = `AI: ${strategyName}`;

  // ── Create a strategy row so the user keeps it ──────────────────────────
  const strategyConfig = {
    symbol,
    execution_interval: effectiveInterval,
    ...(analysisInterval ? { analysis_interval: analysisInterval } : {}),
    commission_pct: 0.1,
    slippage_pct: 0.05,
  };

  const { data: strategy, error: strategyError } = await supabase
    .from("strategies")
    .insert({
      user_id: user.id,
      name: strategyName,
      description: `${generated.description}${goal ? `\n\nGoal: ${goal}` : ""}\n\n[Generated by AI Strategy Mode]`,
      code: generated.code,
      config: strategyConfig,
    } as any)
    .select("id")
    .single();

  if (strategyError || !strategy) {
    return { error: `Could not save strategy: ${strategyError?.message}` };
  }

  // ── Build config (stored in Supabase) ───────────────────────────────────
  const config = {
    strategy_id: strategy.id,
    name: runName,
    symbol,
    interval: effectiveInterval,
    ...(analysisInterval ? { analysis_interval: analysisInterval } : {}),
    start: null,
    end: null,
    entry: generated.entry,
    risk: generated.risk,
    params: generated.params,
    // AI metadata — read back on the results page
    ai_risk: risk,
    ai_timeframe: timeframe,
    ai_goal: goal || null,
  };

  // ── Insert pending backtest run ──────────────────────────────────────────
  const { data: run, error: runError } = await supabase
    .from("backtest_runs")
    .insert({
      user_id: user.id,
      strategy_id: strategy.id,
      status: "pending",
      config: config as unknown as Record<string, unknown>,
    } as any)
    .select("id")
    .single();

  if (runError || !run) {
    return { error: `Could not create backtest: ${runError?.message}` };
  }

  // ── POST to FastAPI ──────────────────────────────────────────────────────
  const apiUrl = process.env.NEXT_PUBLIC_BACKTEST_API_URL || "http://localhost:8000";
  const { data: { session } } = await supabase.auth.getSession();

  const payload: BacktestRunRequest = {
    run_id: run.id,
    symbol,
    interval: effectiveInterval,
    ...(analysisInterval ? { analysis_interval: analysisInterval } : {}),
    start: null,
    end: null,
    entry: generated.entry,
    risk: generated.risk,
    params: generated.params,
    name: runName,
  };

  try {
    const apiRes = await fetch(`${apiUrl}/backtests/run`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${session?.access_token}`,
      },
      body: JSON.stringify(payload),
    });

    if (!apiRes.ok) {
      const errBody = await apiRes.json().catch(() => null);
      const detail = errBody?.detail || apiRes.statusText;
      await supabase
        .from("backtest_runs")
        .update({ status: "failed", error_message: `API error: ${detail}` })
        .eq("id", run.id);
      return { error: `Backtest engine error: ${detail}` };
    }
  } catch {
    await supabase
      .from("backtest_runs")
      .update({ status: "failed", error_message: "Could not reach backtest engine." })
      .eq("id", run.id);
    return { error: "Could not connect to the backtest engine. Please try again later." };
  }

  redirect(`/dashboard/ai-strategy/${run.id}`);
}
