"use server";

import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { generateStrategy } from "@/lib/ai-strategy";
import type { RiskLevel, TimeframeHorizon } from "@/lib/ai-strategy";
import type { BacktestRunRequest } from "@/types";

export async function generateAndTestStrategyAction(formData: FormData) {
  const supabase = createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) throw new Error("Not authenticated");

  const risk = (formData.get("risk") as RiskLevel) || "balanced";
  const timeframe = (formData.get("timeframe") as TimeframeHorizon) || "medium";
  const symbol = (formData.get("symbol") as string) || "SPY";
  const goal = (formData.get("goal") as string) || "";

  // ── Generate strategy config ────────────────────────────────────────────
  const generated = generateStrategy(risk, timeframe);
  const runName = `AI: ${generated.name} on ${symbol}`;

  // ── Create a strategy row so the user keeps it ──────────────────────────
  const { data: strategy, error: strategyError } = await supabase
    .from("strategies")
    .insert({
      user_id: user.id,
      name: generated.name,
      description: `${generated.description}${goal ? `\n\nGoal: ${goal}` : ""}\n\n[Generated by AI Strategy Mode]`,
      code: generated.code,
    })
    .select("id")
    .single();

  if (strategyError || !strategy) {
    return { error: `Could not save strategy: ${strategyError?.message}` };
  }

  // ── Build config (stored in Supabase) ───────────────────────────────────
  const config = {
    strategy_id: strategy.id,
    name: runName,
    symbol,
    interval: generated.interval,
    start: null,
    end: null,
    entry: generated.entry,
    risk: generated.risk,
    params: generated.params,
    // AI metadata — read back on the results page
    ai_risk: risk,
    ai_timeframe: timeframe,
    ai_goal: goal || null,
  };

  // ── Insert pending backtest run ──────────────────────────────────────────
  const { data: run, error: runError } = await supabase
    .from("backtest_runs")
    .insert({
      user_id: user.id,
      strategy_id: strategy.id,
      status: "pending",
      config: config as unknown as Record<string, unknown>,
    })
    .select("id")
    .single();

  if (runError || !run) {
    return { error: `Could not create backtest: ${runError?.message}` };
  }

  // ── POST to FastAPI ──────────────────────────────────────────────────────
  const apiUrl = process.env.NEXT_PUBLIC_BACKTEST_API_URL || "http://localhost:8000";
  const { data: { session } } = await supabase.auth.getSession();

  const payload: BacktestRunRequest = {
    run_id: run.id,
    symbol,
    interval: generated.interval,
    start: null,
    end: null,
    entry: generated.entry,
    risk: generated.risk,
    params: generated.params,
    name: runName,
  };

  try {
    const apiRes = await fetch(`${apiUrl}/backtests/run`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${session?.access_token}`,
      },
      body: JSON.stringify(payload),
    });

    if (!apiRes.ok) {
      const errBody = await apiRes.json().catch(() => null);
      const detail = errBody?.detail || apiRes.statusText;
      await supabase
        .from("backtest_runs")
        .update({ status: "failed", error_message: `API error: ${detail}` })
        .eq("id", run.id);
      return { error: `Backtest engine error: ${detail}` };
    }
  } catch {
    await supabase
      .from("backtest_runs")
      .update({ status: "failed", error_message: "Could not reach backtest engine." })
      .eq("id", run.id);
    return { error: "Could not connect to the backtest engine. Please try again later." };
  }

  redirect(`/dashboard/ai-strategy/${run.id}`);
}
